name: GitHub Pages Deployment

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '05 00 * * *'
  workflow_dispatch:

env:
  JEKYLL_DEBUG: true

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: 'docs'
          jekyll_build_options: '--drafts'
          target_branch: 'gh-pages'